const apartments = [
  {
    id: 1,
    title: 'Plaza Mayor',
    location: 'Calle Compañía, habitación doble con balcón e internet incluido',
    price: 450,
    rooms: 4,
    bathrooms: 2,
    image: 'PlazaMayor',
  },
  {
    id: 2,
    title: 'Piso Zona Universitaria',
    location: 'Habitación doble con estilo mediterráneo, amueblado y cerca de la universidad',
    price: 380,
    rooms: 3,
    bathrooms: 2,
    image: 'Retiro',
  },
  {
    id: 3,
    title: 'Barrio Salamanca',
    location: 'Habitación individual con baño en suite, aire acondicionado y cerca de tiendas',
    price: 520,
    rooms: 5,
    bathrooms: 2,
    image: 'BarrioSalamanca',
  },
  {
    id: 4,
    title: 'Malasaña',
    location: 'Habitación individual en piso reformado, ambiente joven y muy bien comunicado',
    price: 410,
    rooms: 3,
    bathrooms: 3,
    image: 'Malasaña',
  },
  {
    id: 5,
    title: 'Chamberí',
    location: 'Habitación doble luminosa, cocina equipada y calefacción central',
    price: 470,
    rooms: 4,
    bathrooms: 3,
    image: 'Chamberi',
  },
  {
    id: 6,
    title: 'La Latina',
    location: 'Habitación con terraza compartida, ambiente tranquilo y cerca del centro',
    price: 430,
    rooms: 3,
    bathrooms: 1,
    image: 'LaLatina',
  },
  {
    id: 7,
    title: 'Chueca',
    location: 'Habitación doble con escritorio, wifi de alta velocidad incluido y baño privado',
    price: 395,
    rooms: 3,
    bathrooms: 3,
    image: 'Chueca',
  },
  {
    id: 8,
    title: 'Piso Zona Centro',
    location: 'Habitación doble con baño privado, gastos incluidos',
    price: 500,
    rooms: 5,
    bathrooms: 4,
    image: 'ZonaCentro',
  },
  {
    id: 9,
    title: 'Piso Zona Tranquila',
    location: 'Habitación individual en zona residencial, ideal para estudiar',
    price: 360,
    rooms: 2,
    bathrooms: 4,
    image: 'ZonaTranquila',
  },
  {
    id: 10,
    title: 'Argüelles',
    location: 'Habitación doble con balcón, cerca de parques y transporte público',
    price: 440,
    rooms: 4,
    bathrooms: 4,
    image: 'Argüelles',
  },
    {
    id: 11,
    title: 'Lavapiés',
    location: 'Habitación individual en piso multicultural, ambiente animado y bien comunicado',
    price: 375,
    rooms: 3,
    bathrooms: 1,
    image: 'Lavapies',
  },
  {
    id: 12,
    title: 'Piso Zona Norte',
    location: 'Habitación doble con armario empotrado, cerca de zonas verdes',
    price: 460,
    rooms: 4,
    bathrooms: 2,
    image: 'ZonaNorte',
  },
];


export default apartments;